version: "3.9"

services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: "hotel-app"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7